List<Map<String, dynamic>> data = [
  {
    "product_Name": "Alba",
    "product_pic": "images/re2.jpeg",
    "product_id": 1,
    "product_description": "Made in Germany",
    "product_price": "150",
  },
  {
    "product_Name": "Accurist",
    "product_pic": "images/re3.jpeg",
    "product_id": 2,
    "product_description": "Made in Germany",
    "product_price": "150",
  },
  {
    "product_Name": "Apple",
    "product_pic": "images/re4.png",
    "product_id": 3,
    "product_description": "Made in Germany",
    "product_price": "150",
  },
  {
    "product_Name": "Brellum",
    "product_pic": "images/re5.png",
    "product_id": 4,
    "product_description": "Made in Germany",
    "product_price": "150",
  },
  {"product_Name": "Dior",
    "product_pic": "images/we2.png",
    "product_id": 5,
    "product_description": "Made in Germany",
    "product_price": 100,
  },
  {"product_Name": "Duvit",
    "product_pic": "images/we1.png",
    "product_id": 6,
    "product_description": "Made in Europe",
    "product_price": 200,
  },
  {"product_Name": "Century",
    "product_pic": "images/we3.png",
    "product_id": 7,
    "product_description": "Made in Germany",
    "product_price": 120,
  },
];
