List<Map<String, dynamic>> Men = [
  {
    "product_Name": "Alba",
    "product_pic": "images/re2.jpeg",
    "product_id": "1",
    "product_description": "Made in Germany",
    "product_price": 199,
  },
  {
    "product_Name": "Accurist",
    "product_pic": "images/re3.jpeg",
    "product_id": "2",
    "product_description": "Made in Canada",
    "product_price": 250,
  },
  {
    "product_Name": "Apple",
    "product_pic": "images/re4.png",
    "product_id": "3",
    "product_description": "Made in Italy",
    "product_price": 170,
  },
  {
    "product_Name": "Brellum",
    "product_pic": "images/re5.png",
    "product_id": "4",
    "product_description": "Made in UK",
    "product_price": 180,
  },
  {
    "product_Name": "Casio",
    "product_pic": "images/we1.png",
    "product_id": "5",
    "product_description": "Made in France",
    "product_price": 199,
  },
  {
    "product_Name": "Cartier",
    "product_pic": "images/we2.png",
    "product_id": "6",
    "product_description": "Made in Canada",
    "product_price": 250,
  },
  {
    "product_Name": "Piaget",
    "product_pic": "images/we3.png",
    "product_id": "7",
    "product_description": "Made in UAE",
    "product_price": 170,
  },
  {
    "product_Name": "Hublert",
    "product_pic": "images/me1.png",
    "product_id": "8",
    "product_description": "Made in Korea",
    "product_price": 100,
  },{
    "product_Name": "ANIME",
    "product_pic": "images/me2.png",
    "product_id": "9",
    "product_description": "Made in Japan ",
    "product_price": 250,
  },{
    "product_Name": "BURJ",
    "product_pic": "images/me3.png",
    "product_id": "10",
    "product_description": "Made in UAE ",
    "product_price": 225,
  },{
    "product_Name": "PARIS",
    "product_pic": "images/me4.png",
    "product_id": "100",
    "product_description": "Made in  France",
    "product_price":119 ,
  },{
    "product_Name": "BEY",
    "product_pic": "images/me5.png",
    "product_id": "12",
    "product_description": "Made in Turkey  ",
    "product_price":150 ,
  },{
    "product_Name": "NIGA",
    "product_pic": "images/me6.png",
    "product_id": "13",
    "product_description": "Made in  Nigeria",
    "product_price": 299,
  }
];
